apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-o7ut
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-o7ut
    app.kubernetes.io/part-of: my-app-1
  name: devfile-sample-go-basic-o7ut
  namespace: abhindas-tenant
spec:
  path: /
  port:
    targetPort: 8079
  to:
    kind: Service
    name: devfile-sample-go-basic-o7ut
    weight: null
status: {}
